### ISSUE TITLE
Not install

### ISSUE THREAD

**Issue by nayankyada** [OpenSecurityResearch/hostapd-wpe#12]
in kali linux 2016.2 amd64 

error at     apt-get install libssl-dev libnl-dev
Unable to locate package libssl-dev
E: Unable to locate package libnl-dev

**Comment by nayankyada** [comment]
![screenshot from 2016-09-08 07-33-56](https://cloud.githubusercontent.com/assets/21226713/18352282/6ee2c576-75fb-11e6-81ce-a7c468f155de.png)

**Comment by nayankyada** [comment]
what to do.........

**Comment by newclem** [comment]
search for libnl-3-dev and libnl-genl-3-dev
and for ssl.h try google

**Comment by nayankyada** [comment]
Thanks...
