### ISSUE TITLE
Hostapd-WPE does not capture EAP-GTC

### ISSUE THREAD

**Issue by W00t3k** [OpenSecurityResearch/hostapd-wpe#25]
https://twitter.com/W00Tock/status/1019251419310972930

Edit file "hostapd-wpe.eap_user" (You can replace PEAP with FAST)

* PEAP [ver=1] 
"t" GTC "password" [2]
# ./hostapd-wpe hostapd-wpe.conf -ddddd 

-snip- EAP-GTC: Response password: -snip-

By configuring the eap)user file, you can request from Apple and Android devices a GTC clear text password - which is shown in the debug console, but is currently not logged.

Thank you very much.

**Comment by 0ca** [comment]
Thanks @W00t3k, that works!

I'm putting again the correct config here in a code block, because the `*` was interpreted as github markdown. Replace last two lines of `hostapd-wpe.eap_user` with:
```
*	PEAP [ver=1]
"t"	GTC "password" [2]
```

**Comment by W00t3k** [comment]
How can we make sure this is documented, and the README is updated?
